### ISSUE TITLE
Add update variants for uncancellable side effects?

### ISSUE THREAD

**Issue by Minnozz** [bloodyowl/rescript-react-update#11]
I often end up writing
```res
({state, send}) => {
  mySideEffect()
  None
}
```

while I would like to write
```res
({state, send}) => mySideEffect()
```

What do you think about adding variants that wrap the returned side effect in a function returning `None`?

For instance (but preferrably with a better/shorter name):

```res
type rec update<'action, 'state> =
  | NoUpdate
  | Update('state)
  | UpdateWithSideEffects('state, self<'action, 'state> => option<unit => unit>)
  | UpdateWithUncancellableSideEffects('state, self<'action, 'state> => unit)
  | SideEffects(self<'action, 'state> => option<unit => unit>)
  | UncancellableSideEffects(self<'action, 'state> => unit)
```

I know I can use the `Legacy` module for this, but sometimes I do want cancellation for some side effects.

**Comment by bloodyowl** [comment]
Hi!

I don't think that this is something that I want to push. I find it actually good that the API makes you explicitly write "I don't have cancellation for that effect" (same goes for RescriptReact's useEffect).

**Comment by Minnozz** [comment]
I understand, thanks for the quick response 👍
