### ISSUE TITLE
Sometimes it dispatches twice

### ISSUE THREAD

**Issue by nickretallack** [bloodyowl/rescript-react-update#14]
The first time I click on the button in this component...

```rescript
@react.component
let make = () => {
  let (_state, send) = ReactUpdate.useReducer((state: int, _action: unit) => {
    Js.log("Handled Action")
    ReactUpdate.Update(state + 1)
  }, 0)

  <button
    onClick={_event => {
      Js.log("Sent Action")
      send()
    }}>
    {React.string("Send Action")}
  </button>
}
```

It logs:

```
Sent Action
Handled Action
Handled Action
```

But subsequent clicks log this instead:

```
Sent Action
Handled Action
```

However, in a more complex app, the doubled output shows up quite often, not just the first time.

Why is this?  Can you fix it?  Unfortunately my app doesn't handle double-dispatched actions well.

This problem manifests in both version 3 and version 4.

**Comment by bloodyowl** [comment]
Hi! This is normal behavior due to the fact we use React's `useReducer` under the hood (https://github.com/facebook/react/issues/16295)

That shouldn't affect the behavior in your app if your reducer itself is pure.
