### ISSUE TITLE
Generate side effect from `getInitialState`?

### ISSUE THREAD

**Issue by Minnozz** [bloodyowl/rescript-react-update#9]
Hi!

I really like this library for managing state in my applications. One thing I miss is being able to generate a side effect from the initial state. I see a few possible APIs for this:
* Return an `update` instead of a `state` from `getInitialState`. `NoUpdate` would be problematic.
* Also return a side effect from `getInitialState`
* Pass `send` to `getInitialState` so an `action` can be sent that generates the side effect later

What are your thoughts about this? Or do you have a way of doing this with the current API?

**Comment by bloodyowl** [comment]
By definition the initial state needs to be valid, default state, meaning we can't return a side effect from this function. 

Have you tried sending the action in a `useEffect0`? If so what's the issue with it?

**Comment by Minnozz** [comment]
I didn't try that yet, but that seems like a good solution. Thanks!
